# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarray=np.array([1 , 3 ,5 , 75 ,8]  , np.int8)

In [3]:
myarray

array([ 1,  3,  5, 75,  8], dtype=int8)

In [4]:
myarray.dtype

dtype('int8')

In [5]:
myarray.shape


(5,)

In [6]:
myarray[2]

5

# array creation: conversion from other python structure

In [7]:
listarray=np.array([[1 , 3 , 5 , 7] , [2 , 3 , 4 , 6 ] , [1 , 2 , 8 , 9]])

In [8]:
listarray

array([[1, 3, 5, 7],
       [2, 3, 4, 6],
       [1, 2, 8, 9]])

In [9]:
listarray.shape


(3, 4)

In [10]:
listarray.size

12

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray[1 , 2]=45

In [13]:
listarray

array([[ 1,  3,  5,  7],
       [ 2,  3, 45,  6],
       [ 1,  2,  8,  9]])

In [14]:
listarray[2 , 2]

8

# Intrinsic NumPy array creation functions

In [15]:
zeros=np.zeros((2 , 4))


In [16]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
rng = np.arange(2 , 45) 

In [18]:
rng

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44])

In [19]:
lspace=np.linspace(2 , 5 , num=5)

** The num=5 parameter in np.linspace(2, 5, num=5) means we want to create 5 equally spaced numbers between 2 and 5. Imagine we have a line starting from 2 and ending at 5. We want to divide this line into 5 equal parts, and the numbers we get at the points where we made these divisions are the values in the array lspace *


In [20]:
lspace

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [21]:
emp=np.empty((3 ,4 ))

In [22]:
emp

array([[1.29506834e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 5.64233733e-067, 7.73444956e-091,
        1.17713297e-047],
       [3.57280452e-062, 1.52079024e-051, 3.99910963e+252,
        8.34402701e-309]])

In [23]:
emp_like=np.empty_like(lspace)

In [24]:
emp_like

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [25]:
p_aray=np.array([[2 , 5 , 6 ,22] , [1 , 3 , 5 , 6]])

In [26]:
p_like=np.empty_like(p_aray)

In [27]:
p_like

array([[       1,        1,        0,      610],
       [    1164,        0, 16777984,    32762]])

In [28]:
ide=np.identity(40)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
arr=np.arange(100)

In [31]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
arr = arr.reshape(4 ,25)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
arr.shape

(4, 25)

In [35]:
arr=arr.ravel()

In [36]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
arr.shape

(100,)

# numpy axis 

In [38]:
x =[[1 , 2 , 3 ,4] , [5 ,6 ,7 , 8 ] , [9 , 10 , 11 , 12]]

In [39]:
ar=np.array(x)

In [40]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
ar.sum(axis=0)

array([15, 18, 21, 24])

In [42]:
ar.sum(axis=1)

array([10, 26, 42])

# numpy methods and atrributes in one dimensional

<em> transposing colum to row and row to column</em>

In [43]:
ar.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Itreator in numpy

<em> (.flat} is used to iterate in numpy</em>

In [44]:
x=[[1 , 2 , 3 ,5] , [4 ,5  ,7 , 74]]

In [45]:
ara=np.array(x)

In [46]:
for item in ara.flat:
    print(item)

1
2
3
5
4
5
7
74


In [47]:
ara.ndim

2

In [48]:
ara.size

8

<em> this nbytes shows total bytes comsumed by an array </em>

In [49]:
ara.nbytes

32

In [50]:
ara.dtype

dtype('int32')

In [51]:
one=np.array([11 , 45 , 15 ,6])

In [52]:
one.argmax()

1

<em> argmax() returns the position(indices) of a maximum value in an array </em>

In [53]:
one.argmin()

3

In [54]:
one.argsort()

array([3, 0, 2, 1], dtype=int64)

# numpy methods and atrributes in two dimensional

In [55]:
two=[[9 ,  4 ,6 ,7] , [4 ,5 ,6 , 7] , [ 4, 2 , 3 ,2]]

In [56]:
twar=np.array(two)

In [57]:
twar

array([[9, 4, 6, 7],
       [4, 5, 6, 7],
       [4, 2, 3, 2]])

In [58]:
twar.argmin()

9

In [59]:
twar.argmax()

0

In [60]:
twar.argmax(axis=0)

array([0, 1, 0, 0], dtype=int64)

In [61]:
twar.argmin(axis=1)

array([1, 0, 1], dtype=int64)

In [62]:
twar.argsort(axis=1)

array([[1, 2, 3, 0],
       [0, 1, 2, 3],
       [1, 3, 2, 0]], dtype=int64)

In [63]:
twar.argsort(axis=0)

array([[1, 2, 2, 2],
       [2, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int64)

In [64]:
twar.ravel()

array([9, 4, 6, 7, 4, 5, 6, 7, 4, 2, 3, 2])

In [65]:
twar.size

12

In [66]:
twar.reshape(12 , 1)

array([[9],
       [4],
       [6],
       [7],
       [4],
       [5],
       [6],
       [7],
       [4],
       [2],
       [3],
       [2]])

In [67]:
two2=[[0 ,  2 ,6 ,7] , [7 ,5 ,8 , 7] , [ 8, 2 , 4 ,2]]

In [68]:
twar2=np.array(two2)

In [69]:
twar2

array([[0, 2, 6, 7],
       [7, 5, 8, 7],
       [8, 2, 4, 2]])

In [70]:
twar

array([[9, 4, 6, 7],
       [4, 5, 6, 7],
       [4, 2, 3, 2]])

In [71]:
twar + twar2

array([[ 9,  6, 12, 14],
       [11, 10, 14, 14],
       [12,  4,  7,  4]])

In [72]:
twar * twar2

array([[ 0,  8, 36, 49],
       [28, 25, 48, 49],
       [32,  4, 12,  4]])

In [73]:
np.sqrt(twar)

array([[3.        , 2.        , 2.44948974, 2.64575131],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.        , 1.41421356, 1.73205081, 1.41421356]])

In [74]:
twar

array([[9, 4, 6, 7],
       [4, 5, 6, 7],
       [4, 2, 3, 2]])

In [75]:
twar.sum()

59

In [76]:
twar.max()

9

In [77]:
twar.min()

2

# finding greater than given num in an array

In [78]:
twar

array([[9, 4, 6, 7],
       [4, 5, 6, 7],
       [4, 2, 3, 2]])

In [79]:
np.where(twar > 6)

(array([0, 0, 1], dtype=int64), array([0, 3, 3], dtype=int64))

In [80]:
a=np.arange(0 , 10)

In [81]:
for item in a:
    print(item)

0
1
2
3
4
5
6
7
8
9


In [82]:
np.where(a >5 )

(array([6, 7, 8, 9], dtype=int64),)

In [83]:
np.count_nonzero(twar)

12

In [84]:
twar2

array([[0, 2, 6, 7],
       [7, 5, 8, 7],
       [8, 2, 4, 2]])

In [85]:
twar2[2 , 2 ]=0

In [86]:
twar2

array([[0, 2, 6, 7],
       [7, 5, 8, 7],
       [8, 2, 0, 2]])

In [90]:
np.count_nonzero(twar2)

10

<em> it counts non zero element in an array </em>

In [91]:
twar2.dtype

dtype('int32')

In [92]:
twar2

array([[0, 2, 6, 7],
       [7, 5, 8, 7],
       [8, 2, 0, 2]])

In [93]:
np.real(twar2)

array([[0, 2, 6, 7],
       [7, 5, 8, 7],
       [8, 2, 0, 2]])

In [94]:
twar2.argmin(axis=0)

array([0, 0, 2, 2], dtype=int64)

# generates a random ones arrary 

In [97]:
s=[2 ,2 ]

In [100]:
one=np.ones(s)

In [101]:
one

array([[1., 1.],
       [1., 1.]])

# 1. indexing and slicing an array

In [102]:
one[0 , 1]

1.0

In [103]:
one[0 , 1]=2

In [104]:
one

array([[1., 2.],
       [1., 1.]])

In [107]:
np.real(one)

array([[1., 2.],
       [1., 1.]])

# 2. array operations

In [110]:
x=[ [1 , 32, 5  ,23] , [45 ,34 ,32 ,3]  ,[ 6 , 7 ,8 ,2]]

In [111]:
y=[[4 , 6 ,2 ,32] , [8 ,35, 65,7] , [2 ,4 ,2 ,6]]

In [112]:
xar=np.array(x)

In [113]:
yar=np.array(y)

In [114]:
xar

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2]])

In [116]:
yar

array([[ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

In [119]:
np.sum(x , axis=0)

array([52, 73, 45, 28])

In [120]:
xar+yar

array([[ 5, 38,  7, 55],
       [53, 69, 97, 10],
       [ 8, 11, 10,  8]])

In [121]:
np.mean(xar)

16.5

In [122]:
np.mean(x)

16.5

In [123]:
np.mean(yar)

14.416666666666666

In [124]:
np.max(xar)

45

In [125]:
np.mean(yar)

14.416666666666666

In [126]:
xar

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2]])

In [127]:
yar

array([[ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

# 3.array manipulation

In [128]:
x

[[1, 32, 5, 23], [45, 34, 32, 3], [6, 7, 8, 2]]

In [129]:
y

[[4, 6, 2, 32], [8, 35, 65, 7], [2, 4, 2, 6]]

In [130]:
xar

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2]])

In [131]:
yar

array([[ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

In [145]:
con=np.concatenate((xar , yar), axis=0)

In [146]:
con

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2],
       [ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

In [148]:
np.size(con)

24

In [153]:
con.reshape(2 , 12)

array([[ 1, 32,  5, 23, 45, 34, 32,  3,  6,  7,  8,  2],
       [ 4,  6,  2, 32,  8, 35, 65,  7,  2,  4,  2,  6]])

In [154]:
a=np.arange(10)

In [171]:
np.split(a  ,[3 , 8])

[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([8, 9])]

<em> 0 dekin 3 samman euta ani 3 dekhin arko  ani 8 dekhin arko </em>

<em>deko number dkhin arko banauxa </em>

In [173]:
xar

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2]])

In [174]:
yar

array([[ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

In [175]:
xar.T

array([[ 1, 45,  6],
       [32, 34,  7],
       [ 5, 32,  8],
       [23,  3,  2]])

<em> trnspose convert row to column and column to row </em>

In [177]:
np.transpose(yar)

array([[ 4,  8,  2],
       [ 6, 35,  4],
       [ 2, 65,  2],
       [32,  7,  6]])

In [178]:
xar

array([[ 1, 32,  5, 23],
       [45, 34, 32,  3],
       [ 6,  7,  8,  2]])

In [179]:
yar

array([[ 4,  6,  2, 32],
       [ 8, 35, 65,  7],
       [ 2,  4,  2,  6]])

In [183]:
np.stack((xar , yar) , axis=1)

array([[[ 1, 32,  5, 23],
        [ 4,  6,  2, 32]],

       [[45, 34, 32,  3],
        [ 8, 35, 65,  7]],

       [[ 6,  7,  8,  2],
        [ 2,  4,  2,  6]]])

In [189]:
np.stack((xar ,yar) , axis=0)

array([[[ 1, 32,  5, 23],
        [45, 34, 32,  3],
        [ 6,  7,  8,  2]],

       [[ 4,  6,  2, 32],
        [ 8, 35, 65,  7],
        [ 2,  4,  2,  6]]])

In [190]:
np.stack((xar , yar) , axis=-1)

array([[[ 1,  4],
        [32,  6],
        [ 5,  2],
        [23, 32]],

       [[45,  8],
        [34, 35],
        [32, 65],
        [ 3,  7]],

       [[ 6,  2],
        [ 7,  4],
        [ 8,  2],
        [ 2,  6]]])

# array iteration